---
- name: Deploy web server on VM1 and VM2
  hosts: webservers
  become: yes
  vars:
    # Set server_number based on the hostname in the inventory file.
    server_number: "{{ '1' if inventory_hostname == 'vm1' else '2' }}"
  tasks:
    - name: Update apt cache and install Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Configure Apache to listen on port 8080 in ports.conf
      lineinfile:
        path: /etc/apache2/ports.conf
        regexp: '^Listen '
        line: 'Listen 8080'
        backup: yes

    - name: Update default site configuration to use port 8080
      replace:
        path: /etc/apache2/sites-enabled/000-default.conf
        regexp: '(:80)'
        replace: ':8080'
        backup: yes

    - name: Deploy custom index.html file with server message
      copy:
        dest: /var/www/html/index.html
        content: "Hello World from SJSU-{{ server_number }}"
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Restart Apache to apply changes
      service:
        name: apache2
        state: restarted
